'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Rep_OverallCoverageDetailed

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''HSID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HSID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSMonth As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfEMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEMonth As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOrg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Detailed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Detailed As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_Sp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Sp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_FromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FromDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ToDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''repDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Salestab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Salestab As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''RadMultiPage21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage21 As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''txt_CustNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SearchBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchBtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Clear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Clear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadAjaxPanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel4 As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''gvRep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRep As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''txt_CustNo_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustNo_V As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Btn_Seacrh_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Seacrh_V As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Cancel_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Cancel_V As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''gvRepVisited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRepVisited As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadPageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''txt_CustNo_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CustNo_B As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Btn_search_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_search_B As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Clear_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Clear_B As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadAjaxPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel2 As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''gvRepZeroBilled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRepZeroBilled As Global.Telerik.Web.UI.RadGrid
End Class
