'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''PlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolder1 As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''frm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblLoginUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''logout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logout As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''dash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dash As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ilogodash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ilogodash As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''welcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents welcome As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ilogoWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ilogoWelcome As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lblrole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrole As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''M1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P56 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P332 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P332 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P80 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P80 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P84 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P84 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li21 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P85 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P85 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P336 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P336 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li26 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P81 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P81 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P92 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P92 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li15 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P87 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P87 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li16 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P217 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P217 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li17 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P83 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P83 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li18 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P259 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P259 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li19 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P261 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P261 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li20 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P308 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P308 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li23 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P93 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P93 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li24 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P94 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P94 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li25 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P95 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P95 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li261 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li261 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P408 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P408 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li13 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P299 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P299 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M9 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P284 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P284 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P285 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P285 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li11 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P286 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P286 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li12 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P262 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P262 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P402 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P402 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li14 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P387 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P387 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Li22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li22 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P388 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P388 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P65 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P65 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P66 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P66 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P67 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P67 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P82 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P69 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P69 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P79 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P79 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P74 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P74 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P75 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P333 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P333 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P86 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P86 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P70 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P70 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P88 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P88 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P71 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P71 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P375 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P375 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P8 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P218 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P218 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P330 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P330 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P410 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P410 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P288 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P288 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P220 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P220 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P221 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P221 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P266 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P266 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P309 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P309 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P365 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P365 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P366 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P366 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P369 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P369 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P371 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P371 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P315 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P315 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P334 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P334 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P335 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P335 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P377 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P377 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P376 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P376 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P378 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P378 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P400 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P400 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P401 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P401 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P455 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P455 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P11 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P256 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P256 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P91 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P91 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P292 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P292 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P219 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P219 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P305 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P305 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P304 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P304 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P417 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P417 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P3630 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P3630 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P415 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P415 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M15 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P150 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P150 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P151 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P151 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P152 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P152 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P153 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P153 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P154 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P154 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P12 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P97 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P97 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P326 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P326 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M10 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P263 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P263 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P264 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P264 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M7 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A6 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P200 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P201 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P201 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P279 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P279 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P224 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P224 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P374 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P374 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P243 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P243 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P281 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P281 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P251 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P251 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P289 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P289 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P361 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P361 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P372 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P372 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A7 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P202 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P202 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P323 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P323 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P265 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P265 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A9 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P206 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P206 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P298 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P298 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P216 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P216 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P207 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P207 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P204 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P204 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P205 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P205 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P407 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P407 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P212 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P212 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P267 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P267 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P367 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P367 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P282 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P282 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P283 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P283 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P301 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P301 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P306 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P306 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P355 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P355 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P356 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P356 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P357 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P357 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P422 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P422 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P373 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P373 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P416 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P416 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P420 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P420 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P421 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P421 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A8 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P203 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P203 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P106 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P106 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P124 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P124 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P337 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P337 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P121 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P121 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P108 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P108 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P287 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P287 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P123 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P307 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P307 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P327 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P327 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P328 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P328 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P340 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P340 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P341 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P341 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P329 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P329 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P344 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P344 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P383 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P383 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P430 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P430 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A10 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P208 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P208 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P209 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P209 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P384 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P384 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P268 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P268 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P278 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P278 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P210 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P210 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P352 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P352 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P211 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P211 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A11 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P255 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P255 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P360 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P360 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P101 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P101 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P215 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P215 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P104 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P104 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P116 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P116 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A12 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P103 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P103 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P100 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P114 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P114 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P234 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P234 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P115 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P115 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P302 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P302 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P311 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P311 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P317 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P317 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P386 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P386 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P394 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P394 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A13 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P105 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P105 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P254 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P254 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P310 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P310 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P290 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P290 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P294 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P294 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P295 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P295 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P296 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P296 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P342 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P342 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P370 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P370 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P343 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P343 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P345 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P345 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P348 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P348 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P349 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P349 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P385 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P385 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P398 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P398 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P399 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P399 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P403 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P403 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P404 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P404 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P362 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P362 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P363 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P363 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P364 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P364 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P297 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P297 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P300 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P300 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P312 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P312 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P318 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P318 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P319 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P319 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P320 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P320 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P324 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P324 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P325 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P325 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P350 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P350 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P113 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P113 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P109 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P358 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P358 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P405 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P405 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P406 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P406 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P409 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P409 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A14 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P110 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P110 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P111 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P111 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P353 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P353 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P354 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P354 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P338 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P338 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P122 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P122 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P127 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P127 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P339 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P339 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P225 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P225 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P223 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P223 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P227 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P227 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P229 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P229 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P226 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P226 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P230 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P230 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P253 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P253 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P247 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P247 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P250 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P250 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P231 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P231 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P112 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P112 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P245 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P245 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P246 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P246 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P252 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P252 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P321 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P321 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P322 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P322 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P359 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P359 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P379 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P379 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P381 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P381 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P390 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P390 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P393 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P393 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A15 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P117 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P117 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P118 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P118 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P107 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P107 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P119 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P119 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P126 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P126 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P368 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P368 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A16 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P238 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P238 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P102 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P102 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P260 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P260 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P258 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P258 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P380 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P380 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P391 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P391 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A18 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P181 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P181 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A17 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P313 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P313 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P314 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P314 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P257 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P257 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P346 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P346 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P347 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P347 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P351 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P351 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''M6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M6 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P17 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P16 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P382 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P382 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''P15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P15 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''FeaturedContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FeaturedContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
